import React, { createContext, useState } from "react";
import { Utilities } from "@/types/utilities";

export const UtilitiesContext = createContext<Utilities>({
  search: "",
  setSearch: () => {},
  indexTab: undefined,
  setIndexTab: () => {},
  page: 1,
  setPage: () => {},
  creatorsSort: "",
  setCreatorsSort: () => {},
  sortAction: false,
  setSortAction: () => {},
  creatorType: "all",
  setCreatorType: () => {},
  collectionsSort: "",
  setCollectionsSort: () => {},
  creatorCategory: "",
  setCreatorCategory: () => {},
  collectionCategory: "",
  setCollectionCategory: () => {},
  totalVolumeOrder: "desc",
  setTotalVolumeOrder: () => {},
  oneDayChangeOrder: "desc",
  setOneDayChangeOrder: () => {},
  thirtyDayChangeOrder: "desc",
  setThirtyDayChangeOrder: () => {},
  sevenDayChangeOrder: "desc",
  setSevenDayChangeOrder: () => {},
  ownersOrder: "desc",
  setOwnersOrder: () => {},
  itemsOrder: "desc",
  setItemsOrder: () => {},
  collectionNameOrder: "asc",
  setCollectionNameOrder: () => {},
  breadcrumbList: undefined,
  setBreadcrumbList: () => {},
});
