import type { Creators } from "./creators.table";

export interface Collections {
  id: string;
  address?: string /* foreign key to creators.username */;
  average_price?: any;
  banner_image_url?: string;
  category?: string;
  created_at?: string; // type unknown;
  created_date?: string; // type unknown;
  creator_username?: string;
  creators?: Creators; // type unknown;
  description?: string; // type unknown;
  discord_members?: number; // type unknown;
  discord_url?: string; // type unknown;
  external_url?: string; // type unknown;
  featured_image_url?: string;
  fees?: any; // type unknown;
  floor_price?: any; // type unknown;
  instagram_username?: string; // type unknown;
  is_rarity_enabled?: boolean; // type unknown;
  large_image_url?: string; // type unknown;
  market_cap?: any;
  num_owners?: number; // type unknown;
  one_day_average_price?: any; // type unknown;
  one_day_change?: any; // type unknown;
  one_day_difference?: any; // type unknown;
  one_day_sales?: number; // type unknown;
  one_day_sales_change?: any;
  one_day_volume?: any; // type unknown;
  one_hour_average_price?: any; // type unknown;
  one_hour_change?: any; // type unknown;
  one_hour_difference?: any; // type unknown;
  one_hour_sales?: number;
  one_hour_sales_change?: any; // type unknown;
  one_hour_volume?: any; // type unknown;
  safelist_request_status?: string; // type unknown;
  seven_day_average_price?: any;
  seven_day_change?: any;
  seven_day_difference?: any;
  seven_day_sales?: number; // type unknown;
  seven_day_volume?: any; // type unknown;
  six_hour_average_price?: any; // type unknown;
  six_hour_change?: any;
  six_hour_difference?: any;
  six_hour_sales?: number;
  six_hour_sales_change?: any;
  six_hour_volume?: any;
  slug: string;
  symbols?: any[];
  tags?: any[];
  telegram_url?: string /* primary key */;
  thirty_day_average_price?: any;
  thirty_day_change?: any;
  thirty_day_difference?: any;
  thirty_day_sales?: number;
  thirty_day_volume?: any;
  total_sales?: number;
  total_supply?: number;
  total_volume?: any;
  twitter_followers?: number;
  twitter_username?: string;
  type?: string;
}
