import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { base } from "@/libs/airtable";

import React, { useState, useEffect, useContext } from "react";

import {
  CreatorTagsContext,
  CollectionTagsContext,
} from "@/contexts/TagsContext";

import { TagList } from "@/components/TagList";
import { CreatorList } from "@/components/CreatorList";
import { CollectionTable } from "@/components/CollectionTable";
import { BaseLayout } from "@/components/BaseLayout";
import { Title } from "@/components/Title";

import { Tag } from "@/types/tag";

type GetAllTags = {
  baseName: string;
  currentTags: [];
  setState: React.Dispatch<React.SetStateAction<Tag[]>>;
};
const TagsPage: NextPage = () => {
  const AIRTABLE_API_KEY = process.env.NEXT_PUBLIC_AIRTABLE_API_KEY;
  const router = useRouter();
  const { page } = router.query;
  const CreatorTags = useContext(CreatorTagsContext);
  const CollectionTags = useContext(CollectionTagsContext);

  return (
    <div>
      <Head>
        <title>Gachi | Search your favorite anime op and ed animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <section className="mx-auto max-w-7xl mt-12">
          <Title property="h2" addClass="mb-5">
            Creator Tags
          </Title>{" "}
          <div className="mb-10">
            <TagList tags={CreatorTags} />
          </div>
        </section>
        <section className="mx-auto max-w-7xl mt-12">
          <Title property="h2" addClass="mb-5">
            Collection Tags
          </Title>{" "}
          <div className="mb-10">
            <TagList tags={CollectionTags} />
          </div>
        </section>
      </BaseLayout>
    </div>
  );
};

export default TagsPage;
