export type Creator = {
  username: string;
  description?: string;
  avatar: any;
  background: any;
  address: string;
  website_url?: string;
  twitter_id?: string;
  instagram_id?: string;
  discord_url?: string;
  type?: string;
  verified?: boolean;
  listed_at: Date | null | string;
  updatedAt?: Date | null | string;
  collections?: string[];
  category?: string;
  twitter_followers?: number | null;
  discord_members?: number | null;
  upvotes_count?: number;
  tags?: string[];
  token_symbol?: string | false;
  total_volume?: number | null;
  average_volume?: number | null;
  average_floor_price?: number | null;
  total_collections?: number | null;
  total_supply?: number | null;
  total_sales?: number | null;
  background_image?: string;
};
