import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useState, useContext } from "react";

import { CreatorList } from "@/components/CreatorList";
import { CollectionTable } from "@/components/CollectionTable";
import { SearchArea } from "@/components/SearchArea";

import { Mainvisual } from "@/components/Mainvisual";
import { ShowMore } from "@/components/ShowMore";
import { Pagination } from "@/components/Pagination";
import { BaseLayout } from "@/components/BaseLayout";
import { IndexTab } from "@/components/IndexTab";
import { Hr } from "@/components/Hr";
import { Title } from "@/components/Title";
import { LinkButton } from "@/components/LinkButton";

import { Dropdown } from "@/components/Dropdown";

import { CreatorsContext } from "@/contexts/CreatorsContext";
import { CollectionsContext } from "@/contexts/CollectionsContext";
import { UtilitiesContext } from "@/contexts/UtilitiesContext";

import { Creator } from "@/types/creator";
import { Collection } from "@/types/collection";
import { Headline } from "@/components/Headline";
import { BreadCrumbs } from "@/components/BreadCrumbs";
const CollectionsPage: NextPage = () => {
  const router = useRouter();
  const { page } = router.query;
  const creators = useContext(CreatorsContext);
  const collections = useContext(CollectionsContext);
  const collectionsLength = collections.length;

  const { setCollectionsSort } = useContext(UtilitiesContext);

  //const [collectionsMenu, setCollectionMenu] =
  //useState<string[]>(collectionsMenus);

  const collectionSortHandler = () => {
    setCollectionsSort("volume");
    console.log("test");
  };
  return (
    <div>
      <Head>
        <title>Gachi | Search your favorite anime op and ed animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <section className="mx-auto px-5 md:px-8 mt-5 lg:mt-12">
          <div className="mb-5">
            <Headline
              pageTitle="Collections"
              title="Japanese awesome NFT collections List."
              length={collectionsLength}
              label="Collections"
            />
          </div>
          {/*<button onClick={collectionSortHandler}>test sort</button>*/}

          <div className="flex gap-5 justify-between">
            <Dropdown position="left" type="collectionCategories" />
            <Dropdown position="right" type="sortCollections" />
          </div>
          <div className="mb-10">
            {collections && <CollectionTable collections={collections} />}
          </div>
          <div className="flex justify-center mb-20">
            <ShowMore currentPage={page ? Number(page) : 1} />
          </div>
        </section>
        <BreadCrumbs
          list={[
            {
              name: "Home",
              path: "/",
            },
            {
              name: "Collections",
              path: "/collections",
            },
          ]}
        />
      </BaseLayout>
    </div>
  );
};

export default CollectionsPage;
