import { useState } from "react";
import { supabase } from "@/libs/supabase";
import { BaseLayout } from "@/components/BaseLayout";
import Head from "next/head";

export default function Login() {
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState("");
  const [otpToken, setOtpToken] = useState("");

  const [sent, setSent] = useState<boolean>(false);

  const handleLogin = async (email: string) => {
    try {
      setLoading(true);
      const { error } = await supabase.auth.signIn({ email });
      if (error) throw error;
      setSent(true);
      alert("Check your email for the login link!");
    } catch (error) {
      //alert(error.error_description || error.message)
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async () => {
    try {
      setLoading(true);
      const { error } = await supabase.auth.verifyOTP({
        email: email,
        token: otpToken,
        type: "magiclink",
      });
      if (error) throw error;
      setSent(true);
      alert("Login success!");
    } catch (error) {
      //alert(error.error_description || error.message)
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Anisonar | Search your favorite anime op and ed animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <div className="p-5">
          <h1 className="text-center text-2xl text-gray-100 mb-3">
            Login with email.
          </h1>
          <div className="flex flex-center max-w-xl w-full mx-auto rounded bg-gray-800 py-8 px-10 flex-col gap-4">
            <p className="text-gray-100 text-center">
              You will be able to use like function.
            </p>
            <input
              className="block px-5 py-3 rounded bg-white w-full"
              type="email"
              placeholder="Your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <input
              className="block px-5 py-3 rounded bg-white w-full"
              type="text"
              placeholder="One-time password"
              value={otpToken}
              onChange={(e) => setOtpToken(e.target.value)}
            />
            <div className="flex justify-center">
              <button
                onClick={(e) => {
                  e.preventDefault();
                  handleLogin(email);
                }}
                className="block rounded bg-blue-500 text-blue-100 text-center px-10 py-3"
                disabled={loading}
              >
                <span>{loading ? "Loading" : "Send magic link"}</span>
              </button>
            </div>
            <div className="flex justify-center mt-5">
              <button
                onClick={(e) => {
                  e.preventDefault();
                  handleVerify();
                }}
                className="block rounded bg-blue-500 text-blue-100 text-center px-10 py-3"
                disabled={loading}
              >
                <span>{loading ? "Loading" : "Login"}</span>
              </button>
            </div>
          </div>
        </div>
      </BaseLayout>
    </>
  );
}
