import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import { CreatorsList } from "@/components/CreatorsList";
import { CollectionTable } from "@/components/CollectionTable";
import { SearchArea } from "@/components/SearchArea";

import { Mainvisual } from "@/components/Mainvisual";
import { ShowMore } from "@/components/ShowMore";
import { Pagination } from "@/components/Pagination";
import { BaseLayout } from "@/components/BaseLayout";
import { IndexTab } from "@/components/IndexTab";
import { Hr } from "@/components/Hr";
import { Title } from "@/components/Title";
import { LinkButton } from "@/components/LinkButton";

const TagsPage: NextPage = () => {
  const router = useRouter();
  const { page } = router.query;

  return (
    <div>
      <Head>
        <title>Gachi | Search your favorite anime op and ed animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <section className="mx-auto max-w-7xl mt-12">
          <Title property="h2" addClass="mb-5">
            Creator Tags
          </Title>{" "}
          <div className="mb-10">
            <CollectionTable />
          </div>
        </section>
        <section className="mx-auto max-w-7xl mt-12">
          <Title property="h2" addClass="mb-5">
            Collection Tags
          </Title>{" "}
          <div className="mb-10">
            <CollectionTable />
          </div>
        </section>
      </BaseLayout>
    </div>
  );
};

export default TagsPage;
