import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import React, { useContext } from "react";

import { CollectionsContext } from "@/contexts/CollectionsContext";

import { CreatorList } from "@/components/CreatorList";
import { CollectionTable } from "@/components/CollectionTable";
import { SearchArea } from "@/components/SearchArea";

import { Mainvisual } from "@/components/Mainvisual";
import { ShowMore } from "@/components/ShowMore";
import { Pagination } from "@/components/Pagination";
import { BaseLayout } from "@/components/BaseLayout";
import { IndexTab } from "@/components/IndexTab";
import { Hr } from "@/components/Hr";
import { Title } from "@/components/Title";
import { LinkButton } from "@/components/LinkButton";
import { TagList } from "@/components/TagList";

import {
  CreatorTagsContext,
  CollectionTagsContext,
} from "@/contexts/TagsContext";
import { CreatorsContext } from "@/contexts/CreatorsContext";

import { Creator } from "@/types/creator";
import { Collection } from "@/types/collection";
import { Tag } from "@/types/tag";

const KeywordPage: NextPage = () => {
  const router = useRouter();
  const { keyword, page } = router.query;
  const creators = useContext(CreatorsContext);
  const collections = useContext(CollectionsContext);

  const CreatorTags = useContext(CreatorTagsContext);
  const CollectionTags = useContext(CollectionTagsContext);

  const filteredCreators01 = creators.filter(
    (item) =>
      typeof keyword == "string" &&
      //@ts-ignore
      item.username.includes(keyword) == true
  );
  const filteredCreators02 = creators.filter(
    (item) =>
      typeof keyword == "string" &&
      //@ts-ignore
      item.description.includes(keyword) == true
  );
  const origin_filteredCreators = [
    ...filteredCreators01,
    ...filteredCreators02,
  ];
  //重複削除
  const filteredCreators = Array.from(new Set(origin_filteredCreators));

  const filteredCollections = collections.filter(
    (item) =>
      typeof keyword == "string" &&
      //@ts-ignore
      item.slug.includes(keyword) == true
  );
  console.log();
  return (
    <div>
      <Head>
        <title>Gachi | Search your favorite anime op and ed animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <section className="mx-auto max-w-7xl mt-12">
          <h1>Resulut of {keyword}</h1>
        </section>

        <section className="mx-auto max-w-7xl mt-12">
          <Title property="h2" addClass="mb-5">
            Creators
          </Title>
          <div className="mb-10">
            <CreatorList creators={filteredCreators} />
          </div>
        </section>
        <Hr />
        <section className="mx-auto max-w-7xl">
          <Title property="h2" addClass="mb-5">
            Collections
          </Title>{" "}
          <div className="mb-10">
            <CollectionTable collections={filteredCollections} />
          </div>
        </section>
        {/*<div className="flex flex-col gap-10 px-5 mx-auto max-w-7xl">
          <div className="mx-auto">
            <ShowMore currentPage={page ? Number(page) : 1} />
          </div>
  </div>*/}
      </BaseLayout>
    </div>
  );
};

export default KeywordPage;
